services:
  - type: web
    name: elearning-php-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    repo: https://github.com/<shamitambhat>/<elearningwebsite>
    branch: master
