name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Use the correct PHP version for your project

    - name: Install Composer (if needed for PHP dependencies)
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install  # If you're using Composer for PHP dependencies

    - name: Deploy or build your application
      run: |
        echo "Add your build or deploy steps here"
