name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Use the correct PHP version for your project

    - name: Lint HTML and CSS
      run: |
        # Add commands for linting HTML/CSS, if you use any (optional)
        htmlhint index.html  # Example for HTML linting (change as needed)
        stylelint **/*.css  # Example for CSS linting (change as needed)
